# Pandas & Data-Preprocessing

### Q.1) Create a pandas dataframe from a dictionary and display the dataframe.

In [4]:
import pandas as pd
d={'Name': ['John', 'Jane', 'Mike'],
        'Age': [25, 30, 35],
        'City': ['New York', 'London', 'Paris']}
df=pd.DataFrame(d)
print(df)

   Name  Age      City
0  John   25  New York
1  Jane   30    London
2  Mike   35     Paris

### Q.2) Load a CSV file into a pandas dataframe and display the first 5 rows of the dataframe.

###### Dataset:- https://www.kaggle.com/datasets/landlord/icecreamsales

In [15]:
import pandas as pd
df=pd.read_csv("icecreamsales.csv")
df.head(5)

   Temperature  Sales
0           37    292
1           40    228
2           49    324
3           61    376
4           72    440

### Q.3) Load a CSV file into a pandas dataframe and display the last 5 rows of the dataframe.

In [16]:
import pandas as pd
df=pd.read_csv("icecreamsales.csv")
df.tail(5)

    Temperature  Sales
7            81    556
8            75    496
9            64    412
10           53    324
11           40    320

### Q.4) How many rows and columns are there in the above dataframe?

In [21]:
print(f'Rows: {df.shape[0]}, Columns: {df.shape[1]}')

Rows: 12, Columns: 2

### Q.5) Display all the columns of above dataframe?

In [29]:
print(df.columns)

Index(['Temperature', 'Sales'], dtype='object')

### Q.6) What are the data types of each column in the dataframe?

In [38]:
print(f'{df.columns[0]}: {type(df.columns[0])}, {df.columns[1]}: {type(df.columns[1])}')

Temperature: <class 'str'>, Sales: <class 'str'>

### Q.7) Check for null values in dataframe df?

In [39]:
df.isnull()

    Temperature  Sales
0         False  False
1         False  False
2         False  False
3         False  False
4         False  False
5         False  False
6         False  False
7         False  False
8         False  False
9         False  False
10        False  False
11        False  False

### Q.8) Create a new column "Total value" in a pandas dataframe that is the sum of two existing columns i.e Sale Price & Profit?

In [42]:
import pandas as pd
df=pd.read_csv("Computersales.csv")
df["Total value"]=df["Sale Price"]+df["Profit"]
df.head(5)

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year,Total value
0,1,Paul Thomas,M,43,OH,M01-F0024,Desktop,479.99,143.39,Website,January,2018,623.38
1,2,Margo Simms,F,37,WV,GT13-0024,Desktop,1249.99,230.89,Flyer 4,January,2018,1480.88
2,3,Sam Stine,M,26,PA,I3670,Desktop,649.99,118.64,Website,February,2018,768.63
3,4,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,March,2018,472.08
4,5,Jessica Elk,F,55,PA,15M-ED,Laptop,699.99,98.09,Flyer 4,March,2018,798.08

### Q.9) From the above dataframe filter out  records where Age > 40?

In [47]:
df[df["Age"]>40]

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year,Total value
0,1,Paul Thomas,M,43,OH,M01-F0024,Desktop,479.99,143.39,Website,January,2018,623.38
4,5,Jessica Elk,F,55,PA,15M-ED,Laptop,699.99,98.09,Flyer 4,March,2018,798.08
5,6,Sally Struthers,F,45,PA,GT13-0024,Desktop,1249.99,230.89,Flyer 2,April,2018,1480.88
6,7,Michelle Samms,F,46,OH,GA401IV,Laptop,1349.99,180.34,Email,May,2018,1530.33
8,9,Ed Klondike,M,52,OH,81TC00,Laptop,649.99,122.34,Email,July,2018,772.33
9,10,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,August,2018,623.38
10,11,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 3,November,2018,1530.33
11,12,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,November,2018,1480.88
12,13,Jason Case,M,57,PA,81TC00,Laptop,649.99,122.34,Email,November,2018,772.33
13,14,Doug Johnson,M,51,PA,I3670,Desktop,649.99,118.64,Website,December,2018,768.63
14,15,Andy Sands,M,56,OH,MY2J2LL,Tablet,999.99,146.69,Flyer 1,December,2018,1146.68
15,16,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,January,2019,472.08
16,17,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,February,2019,798.08
17,18,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,March,2019,1146.68
19,20,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2019,772.33
20,21,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,May,2019,623.38
21,22,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,August,2019,1530.33
22,23,Paul Thomas,M,43,OH,81TC00,Laptop,649.99,122.34,Website,August,2019,772.33
24,25,Michelle Samms,F,46,NY,I3670,Desktop,649.99,118.64,Flyer 2,November,2019,768.63
26,27,Ed Klondike,M,52,OH,Q526FA,Laptop,1049.99,143.09,Website,December,2019,1193.08
28,29,Jessica Elk,F,55,PA,GA401IV,Laptop,1349.99,180.34,Flyer 2,December,2019,1530.33
29,30,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,January,2020,623.38
30,31,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 1,January,2020,1530.33
31,32,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,February,2020,1480.88
32,33,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,March,2020,472.08
33,34,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,March,2020,798.08
34,35,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,April,2020,1146.68
35,36,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2020,772.33
36,37,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,April,2020,623.38
37,38,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,May,2020,1530.33

### Q.10) Drop State column from dataframe df?

In [54]:
df.drop("State",axis=1)

,Sale ID,Contact,Sex,Age,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year,Total value
0,1,Paul Thomas,M,43,M01-F0024,Desktop,479.99,143.39,Website,January,2018,623.38
1,2,Margo Simms,F,37,GT13-0024,Desktop,1249.99,230.89,Flyer 4,January,2018,1480.88
2,3,Sam Stine,M,26,I3670,Desktop,649.99,118.64,Website,February,2018,768.63
3,4,Moe Eggert,M,35,I3593,Laptop,399.99,72.09,Website,March,2018,472.08
4,5,Jessica Elk,F,55,15M-ED,Laptop,699.99,98.09,Flyer 4,March,2018,798.08
5,6,Sally Struthers,F,45,GT13-0024,Desktop,1249.99,230.89,Flyer 2,April,2018,1480.88
6,7,Michelle Samms,F,46,GA401IV,Laptop,1349.99,180.34,Email,May,2018,1530.33
7,8,Mick Roberts,M,23,MY2J2LL,Tablet,999.99,146.69,Website,July,2018,1146.68
8,9,Ed Klondike,M,52,81TC00,Laptop,649.99,122.34,Email,July,2018,772.33
9,10,Phil Jones,M,56,M01-F0024,Desktop,479.99,143.39,Flyer 2,August,2018,623.38
10,11,Rick James,M,49,GA401IV,Laptop,1349.99,180.34,Flyer 3,November,2018,1530.33
11,12,Sue Etna,F,54,GT13-0024,Desktop,1249.99,230.89,Flyer 2,November,2018,1480.88
12,13,Jason Case,M,57,81TC00,Laptop,649.99,122.34,Email,November,2018,772.33
13,14,Doug Johnson,M,51,I3670,Desktop,649.99,118.64,Website,December,2018,768.63
14,15,Andy Sands,M,56,MY2J2LL,Tablet,999.99,146.69,Flyer 1,December,2018,1146.68
15,16,Kim Collins,F,49,I3593,Laptop,399.99,72.09,Flyer 2,January,2019,472.08
16,17,Edna Sanders,F,46,15M-ED,Laptop,699.99,98.09,Email,February,2019,798.08
17,18,Michelle Samms,F,46,MY2J2LL,Tablet,999.99,146.69,Website,March,2019,1146.68
18,19,Mick Roberts,M,23,I3593,Laptop,399.99,72.09,Flyer 4,March,2019,472.08
19,20,Sally Struthers,F,45,81TC00,Laptop,649.99,122.34,Website,April,2019,772.33
20,21,Jason Case,M,57,M01-F0024,Desktop,479.99,143.39,Flyer 4,May,2019,623.38
21,22,Doug Johnson,M,51,GA401IV,Laptop,1349.99,180.34,Website,August,2019,1530.33
22,23,Paul Thomas,M,43,81TC00,Laptop,649.99,122.34,Website,August,2019,772.33
23,24,Margo Simms,F,37,Q526FA,Laptop,1049.99,143.09,Flyer 4,November,2019,1193.08
24,25,Michelle Samms,F,46,I3670,Desktop,649.99,118.64,Flyer 2,November,2019,768.63
25,26,Mick Roberts,M,23,Q526FA,Laptop,1049.99,143.09,Email,November,2019,1193.08
26,27,Ed Klondike,M,52,Q526FA,Laptop,1049.99,143.09,Website,December,2019,1193.08
27,28,Moe Eggert,M,35,15M-ED,Laptop,699.99,98.09,Email,December,2019,798.08
28,29,Jessica Elk,F,55,GA401IV,Laptop,1349.99,180.34,Flyer 2,December,2019,1530.33
29,30,Phil Jones,M,56,M01-F0024,Desktop,479.99,143.39,Flyer 2,January,2020,623.38
30,31,Rick James,M,49,GA401IV,Laptop,1349.99,180.34,Flyer 1,January,2020,1530.33
31,32,Sue Etna,F,54,GT13-0024,Desktop,1249.99,230.89,Flyer 2,February,2020,1480.88
32,33,Kim Collins,F,49,I3593,Laptop,399.99,72.09,Flyer 2,March,2020,472.08
33,34,Edna Sanders,F,46,15M-ED,Laptop,699.99,98.09,Email,March,2020,798.08
34,35,Michelle Samms,F,46,MY2J2LL,Tablet,999.99,146.69,Website,April,2020,1146.68
35,36,Sally Struthers,F,45,81TC00,Laptop,649.99,122.34,Website,April,2020,772.33
36,37,Jason Case,M,57,M01-F0024,Desktop,479.99,143.39,Flyer 4,April,2020,623.38
37,38,Doug Johnson,M,51,GA401IV,Laptop,1349.99,180.34,Website,May,2020,1530.33
38,39,Moe Eggert,M,35,I3593,Laptop,399.99,72.09,Website,May,2020,472.08

### Q.11) Read a csv file and display the information about the dataframe?
#### Dataset:- https://www.kaggle.com/datasets/rohitsahoo/sales-forecasting

In [91]:
import pandas as pd
df=pd.read_csv("train.csv")
df.describe()

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

### Q.12) Convert the datatype of column Ship Date from object to datetime?

In [100]:
df['Ship Date']= pd.to_datetime(df['Ship Date'])

### Q.13) Convert the datatype of column Sales from float to int?

In [104]:
df["Sales"]=df["Sales"].astype(int)

### Q.14) Drop any rows with null values?

In [82]:
df.dropna()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

### Q.15)  Display the total sales for each region from the above dataframe?

In [77]:
df.groupby('Region')['Sales'].sum()

Region
Central    492646.9132
East       669518.7260
South      389151.4590
West       710219.6845
Name: Sales, dtype: float64

### Q.16) How many unique categories of product are there in the above dataframe?

In [72]:
print(df["Category"].unique())

['Furniture' 'Office Supplies' 'Technology']

### Q.17) How can you replace all missing values in the 'Sales' column with the mean value of that column?

##### Note:- Let us assume there is null values in sales column

In [63]:
df.fillna(df.mean)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

### Q.18) How can you select all rows and columns of a DataFrame using loc?

In [58]:
df.loc[:]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

### Q.19) How can you rename a Sub-Category column to sub Category in  DataFrame df?

In [62]:
df.rename(columns={'Sub-Category': 'sub Category'})

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,sub Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

### Q.20) Display all records from dataframe df where city is Chicago?

In [57]:
df[df['City']=='Chicago']

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
66,67,US-2016-164175,30/04/2016,05/05/2016,Standard Class,PS-18970,Paul Stevenson,Home Office,United States,Chicago,Illinois,60610.0,Central,FUR-CH-10001146,Furniture,Chairs,"Global Value Mid-Back Manager's Chair, Gray",213.115
84,85,US-2018-119662,13/11/2018,16/11/2018,First Class,CS-12400,Christopher Schild,Home Office,United States,Chicago,Illinois,60623.0,Central,OFF-ST-10003656,Office Supplies,Storage,Safco Industrial Wire Shelving,230.376
99,100,CA-2017-158568,29/08/2017,02/09/2017,Standard Class,RB-19465,Rick Bensley,Home Office,United States,Chicago,Illinois,60610.0,Central,OFF-PA-10003256,Office Supplies,Paper,Avery Personal Creations Heavyweight Cards,64.624
100,101,CA-2017-158568,29/08/2017,02/09/2017,Standard Class,RB-19465,Rick Bensley,Home Office,United States,Chicago,Illinois,60610.0,Central,TEC-AC-10001767,Technology,Accessories,SanDisk Ultra 64 GB MicroSDHC Class 10 Memory ...,95.976
101,102,CA-2017-158568,29/08/2017,02/09/2017,Standard Class,RB-19465,Rick Bensley,Home Office,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10002609,Office Supplies,Binders,Avery Hidden Tab Dividers for Binding Systems,1.788
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9747,9748,US-2015-140914,11/11/2015,15/11/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Chicago,Illinois,60653.0,Central,FUR-FU-10000175,Furniture,Furnishings,DAX Wood Document Frame.,10.984
9748,9749,US-2015-140914,11/11/2015,15/11/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Chicago,Illinois,60653.0,Central,FUR-CH-10003379,Furniture,Chairs,Global Commerce Series High-Back Swivel/Tilt C...,797.944
9750,9751,CA-2017-113390,11/10/2017,15/10/2017,Standard Class,EP-13915,Emily Phan,Consumer,United States,Chicago,Illinois,60610.0,Central,OFF-AR-10003183,Office Supplies,Art,Avery Fluorescent Highlighter Four-Color Set,5.344
9751,9752,CA-2017-113390,11/10/2017,15/10/2017,Standard Class,EP-13915,Emily Phan,Consumer,United States,Chicago,Illinois,60610.0,Central,OFF-AR-10001446,Office Supplies,Art,Newell 309,27.720
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.798